CREATE TABLE IF NOT EXISTS rols(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS users(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar NOT NULL, 
    email varchar NOT NULL,
    password varchar NOT NULL,
    id_rol INTEGER REFERENCES rols(id)
);

CREATE TABLE IF NOT EXISTS categorys(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS apps(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL CHECK (name <> ''),
    price decimal NOT NULL,
    description text NOT NULL,
    date timestamp NOT NULL,
    id_user INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS prices(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    price decimal NOT NULL,
    date timestamp NOT NULL,
    id_app INTEGER REFERENCES apps(id)
);

CREATE TABLE IF NOT EXISTS apps_bought(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_user INTEGER REFERENCES users(id),
    id_app INTEGER REFERENCES apps(id),
    date timestamp NOT NULL,
    price decimal NOT NULL
);

CREATE TABLE IF NOT EXISTS list_wishes(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_user INTEGER REFERENCES users(id),
    id_app INTEGER REFERENCES apps(id)
);










